name: Image
concurrency:
  group: image-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - src/**
      - nix/**
      - flake.nix
      - flake.lock

jobs:
  Image:
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GHCTOKEN }}

      - name: Build Image
        run: nix develop .#build -c nixos-generate --flake .#ghc -f amazon
