name: Nix
concurrency:
  group: nix-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - nix/**
      - flake.nix
      - flake.lock

jobs:
  Nix:
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Show
        run: nix flake show

      - name: Check
        run: nix flake check
